### ISSUE TITLE
Unable to unzip chromedriver zip file

### ISSUE THREAD

**Issue by ariyuan** [macacajs/macaca-chromedriver#25]
C:\Users\admin>set CHROMEDRIVER_CDNURL=http://chromedriver.storage.googleapis.co
m

C:\Users\admin>npm i macaca-chromedriver -g
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
C:\Users\admin\AppData\Roaming\npm\macaca-chromedriver -> C:\Users\admin\AppData
\Roaming\npm\node_modules\macaca-chromedriver\bin\macaca-chromedriver

> macaca-chromedriver@1.0.41 install C:\Users\admin\AppData\Roaming\npm\node_mod
ules\macaca-chromedriver
> node ./bin/macaca-chromedriver install

>> version: 2.33
>> chromedriver cdn url: http://chromedriver.storage.googleapis.com/2.33/chromedriver_win32.zip

C:\Users\admin\AppData\Roaming\npm\node_modules\macaca-chromedriver\node_modules
\adm-zip\zipFile.js:66
            throw Utils.Errors.INVALID_FORMAT;
            ^
Invalid or unsupported zip format. No END header found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! macaca-chromedriver@1.0.41 install: `node ./bin/macaca-chromedriver ins
tall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the macaca-chromedriver@1.0.41 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by paradite** [comment]
will take a look in this few days.
@ariyuan did you managed to resolve/walk-around the issue?

**Comment by paradite** [comment]
installs fine on my side, cannot re-produce the issue:
```
$ npm i macaca-chromedriver -g
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
/usr/local/bin/macaca-chromedriver -> /usr/local/lib/node_modules/macaca-chromedriver/bin/macaca-chromedriver

> macaca-chromedriver@1.0.45 install /usr/local/lib/node_modules/macaca-chromedriver
> node ./bin/macaca-chromedriver install

>> version: 2.33
>> chromedriver cdn url: https://chromedriver.storage.googleapis.com/2.33/chromedriver_mac64.zip
>> chromedriver local in /usr/local/lib/node_modules/macaca-chromedriver/exec/chromedriver2.33
+ macaca-chromedriver@1.0.45
added 123 packages from 90 contributors in 9.226s
```
problem is likely with your internet connection.
closing the issue, please raise another one if you still have issues.
