### ISSUE TITLE
Install chromedriver failed

### ISSUE THREAD

**Issue by jackal186** [macacajs/macaca-chromedriver#34]
> node ./bin/macaca-chromedriver install

>> version: 2.45
>> chromedriver cdn url: http://npm.taobao.org/mirrors/chromedriver/2.45/chromedriver_win32.zip
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ETIMEDOUT 114.55.80.225:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! macaca-chromedriver@1.1.2 install: `node ./bin/macaca-chromedriver install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the macaca-chromedriver@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by paradite** [comment]
https://github.com/alibaba/macaca/issues/925
