### ISSUE TITLE
chromedriver version only support less than 73

### ISSUE THREAD

**Issue by balzaron** [macacajs/macaca-chromedriver#35]
on macos i had installed latest 74.0.x chrome, but return an error
i cannot revert the chrome version.
pls fix it .thx
"status":33,"value":{"message":"session not created: Chrome version must be between 70 and 73

**Comment by paradite** [comment]
please create issue here: https://github.com/alibaba/macaca/issues and provide more details.
what command did you run? what's the full output? what's the output of `macaca doctor`?
